name: payan
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluro: ^1.5.1
  provider: ^3.1.0+1
  cupertino_icons: ^0.1.2
  dio: ^2.1.13
  font_awesome_flutter: ^8.5.0
  sticky_headers: "^0.1.7"
  carousel_slider: ^1.3.0
  barcode_scan: ^0.0.3
  url_launcher: ^4.0.1
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/